### ISSUE TITLE
error during mapping with the csv mapper

### ISSUE THREAD

**Issue by CT-Szilvia** [sphereio/csv-mapper#6]
When we run the carhartt-mapping yaml file, we we get an error:
Following command do we use.

node --max-old-space-size=6144 bin/csv-mapper --mapping test-data/carharrt-mapping-rev2.yaml --inCsv test-data/productInCSV.csv --outCsv test-data/SampleOutCSV.csv

Error: Error during mapping from column 'product_family_reference' to column 'categoryUrl' with current value '4b08ab3b-310c-4094-9d83-d494608b3926': TypeError: undefined is not a function

```
at Object.module.exports.transformFirstValue (/Users/sraj/Documents/workspace/csv-mapper-master/lib/util.js:97:62)

at FallbackTransformer.transform (/Users/sraj/Documents/workspace/csv-mapper-master/lib/transformer.js:555:17)

at /Users/sraj/Documents/workspace/csv-mapper-master/lib/util.js:89:28
```

Can someone please take a look? 
I can also send the input files + the yaml file. 
Thanks, 
Szilvia

**Comment by hajoeichler** [comment]
@CT-Szilvia still an issue?
